version: '2'
services:
  web_view:
    image: dim5x/flask:latest
    #build:
    #  context: ../../
    #  dockerfile: ./cicd/docker/flask
    container_name: web_view
    ports:
      - 5000:5000
    networks:
      bridge:
        ipv4_address: 172.21.0.3
    #environment:
    #  POSTGRES_HOST: db
    restart: always
    volumes:
      - ../../local_docker.config:/app/alerter/local.config
      - ../../destination.db:/app/alerter/destination.db
  alerter:
    image: dim5x/alerter:latest
    #build:
    #  context: ../../
    #  dockerfile: ./cicd/docker/alerter
    container_name: alerter
    ports:
      - 514:514/udp
    networks:
      bridge:
        ipv4_address: 172.21.0.2
    #environment:
    #  POSTGRES_HOST: db
    restart: always
    volumes:
      - ../../local_docker.config:/app/alerter/local.config
      - ../../destination.db:/app/alerter/destination.db
networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16
          gateway: 172.21.0.1
